apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-todo-list
  template:
    metadata:
      labels:
        app: react-todo-list
    spec:
      containers:
        - name: react-todo-list
          image: localhost:32000/react-todo-list:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-todo-list-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: react-todo-list
